// Platform-wide referral admin sample data.
// When the backend ships endpoints, swap consumers to useFetchData.

export const PLATFORM = {
  totalReferrals: 3421,
  activeReferrers: 721,
  pendingRewards: 18_200_000,
  unlockedRewards: 4_300_000,
  paidOut: 2_100_000,
  expiringRewards: 5_800_000,
};

export const REFERRERS = [
  {
    id: "tobi",
    name: "Tobi Olarinde",
    email: "tobi@example.com",
    code: "Tobi123",
    referrals: 25,
    pending: 300_000,
    unlocked: 100_000,
    withdrawn: 75_000,
    joined: "2025-08-12",
    businesses: [
      {
        id: "abc",
        name: "ABC Store",
        status: "Active",
        plan: "Growth Plan",
        currentSubscription: 5000,
        totalSubscriptionValue: 15000,
        totalReward: 20000,
        unlocked: 3000,
        pending: 17000,
        expiresInDays: 170,
        activity: [
          { date: "Jun 2", subscription: 5000, reward: 1000 },
          { date: "Jul 2", subscription: 5000, reward: 1000 },
        ],
      },
      {
        id: "fresh",
        name: "Fresh Mart",
        status: "Active",
        plan: "Starter Plan",
        currentSubscription: 4000,
        totalSubscriptionValue: 24000,
        totalReward: 20000,
        unlocked: 8000,
        pending: 12000,
        expiresInDays: 145,
        activity: [
          { date: "May 12", subscription: 4000, reward: 2000 },
          { date: "Jun 12", subscription: 4000, reward: 2000 },
        ],
      },
      {
        id: "dee",
        name: "Dee Pharmacy",
        status: "Not Subscribed",
        plan: "—",
        currentSubscription: 0,
        totalSubscriptionValue: 0,
        totalReward: 20000,
        unlocked: 0,
        pending: 20000,
        expiresInDays: 178,
        activity: [],
      },
    ],
  },
  {
    id: "sarah",
    name: "Sarah Adekunle",
    email: "sarah@example.com",
    code: "Sarah42",
    referrals: 10,
    pending: 150_000,
    unlocked: 40_000,
    withdrawn: 20_000,
    joined: "2025-10-08",
    businesses: [
      {
        id: "kano",
        name: "Kano Foods Co.",
        status: "Active",
        plan: "Growth Plan",
        currentSubscription: 6000,
        totalSubscriptionValue: 18000,
        totalReward: 20000,
        unlocked: 6000,
        pending: 14000,
        expiresInDays: 120,
        activity: [
          { date: "Apr 1", subscription: 6000, reward: 2000 },
          { date: "May 1", subscription: 6000, reward: 2000 },
          { date: "Jun 1", subscription: 6000, reward: 2000 },
        ],
      },
    ],
  },
  {
    id: "ifeanyi",
    name: "Ifeanyi Johnson",
    email: "ifeanyi@example.com",
    code: "IfeJ99",
    referrals: 42,
    pending: 540_000,
    unlocked: 220_000,
    withdrawn: 180_000,
    joined: "2025-06-22",
    businesses: [],
  },
  {
    id: "bola",
    name: "Bola Salami",
    email: "bola.s@example.com",
    code: "Bola21",
    referrals: 6,
    pending: 80_000,
    unlocked: 10_000,
    withdrawn: 0,
    joined: "2026-02-14",
    businesses: [],
  },
  {
    id: "chinedu",
    name: "Chinedu Eze",
    email: "chinedu@example.com",
    code: "Chin77",
    referrals: 18,
    pending: 220_000,
    unlocked: 85_000,
    withdrawn: 60_000,
    joined: "2025-11-30",
    businesses: [],
  },
];

export const findReferrer = (id) => REFERRERS.find((r) => r.id === id);
