// Subscription plans now include usage Limits and Feature toggles
// Limits: number OR null (∞ = Unlimited)
// Features: boolean toggles
export const SUBSCRIPTION_PLANS = [
  {
    id: "basic",
    name: "Basic",
    color: "#B26A00",
    bg: "#FFF7E8",
    price: 4500,
    cycle: "Monthly",
    description:
      "Starter plan for small merchants — essential limits and core features.",
    limits: {
      users: 1,
      attendants: 0,
      outlets: 1,
      sales: 40,
      invoices: 0,
      inventory: 5,
      customers: 50,
    },
    features: {
      bulkEmail: false,
      bulkSms: false,
      inStoreCheckout: true,
      storefront: false,
      trackIncome: true,
      bankExpense: false,
      production: false,
    },
    activeSubscribers: 412,
    revenueMTD: 1854000,
  },
  {
    id: "syncplus",
    name: "Syncplus",
    color: "#3949AB",
    bg: "#EEF2FF",
    price: 9500,
    cycle: "Monthly",
    description:
      "Mid-tier plan for growing businesses — generous limits and standard support.",
    limits: {
      users: 5,
      attendants: 3,
      outlets: 2,
      sales: 500,
      invoices: 100,
      inventory: 250,
      customers: 1000,
    },
    features: {
      bulkEmail: true,
      bulkSms: false,
      inStoreCheckout: true,
      storefront: true,
      trackIncome: true,
      bankExpense: true,
      production: false,
    },
    activeSubscribers: 3210,
    revenueMTD: 30495000,
  },
  {
    id: "syncpro",
    name: "Syncpro",
    color: "#02981D",
    bg: "#E6F7EA",
    price: 25000,
    cycle: "Monthly",
    description:
      "Premium plan for high-volume merchants — unlimited transactions, priority support.",
    limits: {
      users: null, // ∞
      attendants: null,
      outlets: null,
      sales: null,
      invoices: null,
      inventory: null,
      customers: null,
    },
    features: {
      bulkEmail: true,
      bulkSms: true,
      inStoreCheckout: true,
      storefront: true,
      trackIncome: true,
      bankExpense: true,
      production: true,
    },
    activeSubscribers: 1842,
    revenueMTD: 46050000,
  },
  {
    id: "trial",
    name: "Trial",
    color: "#0369A1",
    bg: "#E0F2FE",
    price: 0,
    cycle: "14-day Trial",
    description:
      "Free 14-day trial — automatically downgrades to Free or upgrades to a paid plan.",
    limits: {
      users: 1,
      attendants: 0,
      outlets: 1,
      sales: 50,
      invoices: 10,
      inventory: 10,
      customers: 25,
    },
    features: {
      bulkEmail: false,
      bulkSms: false,
      inStoreCheckout: true,
      storefront: false,
      trackIncome: true,
      bankExpense: false,
      production: false,
    },
    activeSubscribers: 482,
    revenueMTD: 0,
  },
];

export const PLAN_LIMIT_FIELDS = [
  { key: "users", label: "Users (Staff Accounts)" },
  { key: "attendants", label: "Attendants" },
  { key: "outlets", label: "Businesses / Outlets" },
  { key: "sales", label: "Sales / Month" },
  { key: "invoices", label: "Invoices" },
  { key: "inventory", label: "Inventory (Products)" },
  { key: "customers", label: "Customers" },
];

export const PLAN_FEATURE_FIELDS = [
  { key: "bulkEmail", label: "Bulk Email" },
  { key: "bulkSms", label: "Bulk SMS" },
  { key: "inStoreCheckout", label: "In-store Checkout" },
  { key: "storefront", label: "Storefront" },
  { key: "trackIncome", label: "Track Income" },
  { key: "bankExpense", label: "Bank Expense Tracking" },
  { key: "production", label: "Production" },
];

export const SAMPLE_USERS = [
  {
    id: "USR-10001",
    name: "Adaeze Okoro",
    businessName: "Adaeze Beauty Hub",
    type: "Business",
    email: "ada.okoro@example.com",
    phone: "+234 802 123 4567",
    address: "12 Allen Avenue, Ikeja, Lagos",
    plan: "syncpro",
    planStatus: "active",
    status: "active",
    tier: "Tier 3",
    kycStatus: "approved",
    kycRef: { segment: "individual", id: "ind-001" },
    joined: "2025-09-12",
    activeFor: "7 months",
    nextBilling: "2026-05-12",
    startDate: "2025-09-12",
    endDate: "2026-09-12",
    inflow: 14820000,
    outflow: 9420000,
    transactions: 1842,
    commission: 412800,
    deliveries: 312,
    bnplEnabled: true,
    logisticsAutomation: true,
    usage: { attendants: 8, inventory: 412, customers: 1280 },
    outlets: [
      { id: "out-1", name: "Ikeja Branch", location: "Ikeja, Lagos" },
      { id: "out-2", name: "Lekki Branch", location: "Lekki, Lagos" },
    ],
  },
  {
    id: "USR-10002",
    name: "Sunde Logistics Ltd",
    businessName: "Sunde Logistics Ltd",
    type: "Business",
    email: "ops@sundelog.ng",
    phone: "+234 700 222 9988",
    address: "5 Awolowo Rd, Ikoyi, Lagos",
    plan: "syncpro",
    planStatus: "active",
    status: "active",
    tier: "Tier 3",
    kycStatus: "pending",
    kycRef: { segment: "business", id: "biz-001" },
    joined: "2025-11-04",
    activeFor: "5 months",
    nextBilling: "2026-05-04",
    startDate: "2025-11-04",
    endDate: "2026-11-04",
    inflow: 24600000,
    outflow: 18200000,
    transactions: 4218,
    commission: 980200,
    deliveries: 1024,
    bnplEnabled: true,
    logisticsAutomation: true,
    usage: { attendants: 22, inventory: 1840, customers: 3210 },
    outlets: [
      { id: "out-1", name: "Ikoyi HQ", location: "Ikoyi, Lagos" },
      { id: "out-2", name: "Apapa Hub", location: "Apapa, Lagos" },
      { id: "out-3", name: "Abuja Hub", location: "Wuse 2, Abuja" },
    ],
  },
  {
    id: "USR-10003",
    name: "Ifeanyi Johnson",
    businessName: null,
    type: "Individual",
    email: "ifeanyi.j@example.com",
    phone: "+234 803 555 1098",
    address: "44 Bode Thomas, Surulere, Lagos",
    plan: "syncplus",
    planStatus: "active",
    status: "active",
    tier: "Tier 2",
    kycStatus: "approved",
    kycRef: { segment: "individual", id: "ind-002" },
    joined: "2026-01-22",
    activeFor: "3 months",
    nextBilling: "2026-05-22",
    startDate: "2026-01-22",
    endDate: "2026-07-22",
    inflow: 1820000,
    outflow: 1240000,
    transactions: 218,
    commission: 42100,
    deliveries: 18,
    bnplEnabled: false,
    logisticsAutomation: false,
    usage: { attendants: 1, inventory: 88, customers: 312 },
    outlets: [
      { id: "out-1", name: "Surulere Store", location: "Surulere, Lagos" },
    ],
  },
  {
    id: "USR-10004",
    name: "Bola Salami",
    businessName: null,
    type: "Individual",
    email: "bola.s@example.com",
    phone: "+234 805 222 8810",
    address: "8 Ahmadu Bello Way, Kano",
    plan: "trial",
    planStatus: "trial",
    status: "pending",
    tier: "Tier 1",
    kycStatus: "re-upload",
    kycRef: { segment: "individual", id: "ind-003" },
    joined: "2026-04-10",
    activeFor: "12 days",
    nextBilling: "2026-04-24",
    startDate: "2026-04-10",
    endDate: "2026-04-24",
    inflow: 32500,
    outflow: 18000,
    transactions: 6,
    commission: 720,
    deliveries: 1,
    bnplEnabled: false,
    logisticsAutomation: false,
    usage: { attendants: 0, inventory: 4, customers: 8 },
    outlets: [{ id: "out-1", name: "Kano Store", location: "Kano" }],
  },
  {
    id: "USR-10005",
    name: "Chinedu Eze",
    businessName: null,
    type: "Individual",
    email: "chinedu@example.com",
    phone: "+234 809 119 2233",
    address: "27 Lekki Phase 1, Lagos",
    plan: "syncplus",
    planStatus: "expired",
    status: "suspended",
    tier: "Tier 2",
    kycStatus: "rejected",
    kycRef: { segment: "individual", id: "ind-004" },
    joined: "2025-07-18",
    activeFor: "9 months",
    nextBilling: "—",
    startDate: "2025-07-18",
    endDate: "2026-04-01",
    inflow: 4820000,
    outflow: 4720000,
    transactions: 612,
    commission: 89400,
    deliveries: 42,
    bnplEnabled: false,
    logisticsAutomation: true,
    usage: { attendants: 2, inventory: 188, customers: 612 },
    outlets: [
      { id: "out-1", name: "Lekki Phase 1 Store", location: "Lekki, Lagos" },
    ],
  },
  {
    id: "USR-10006",
    name: "Kano Foods Co.",
    businessName: "Kano Foods Co.",
    type: "Business",
    email: "admin@kanofoods.ng",
    phone: "+234 701 444 5566",
    address: "Sabon Gari, Kano",
    plan: "syncpro",
    planStatus: "active",
    status: "active",
    tier: "Tier 3",
    kycStatus: "approved",
    kycRef: { segment: "business", id: "biz-002" },
    joined: "2025-12-01",
    activeFor: "4 months",
    nextBilling: "2026-05-01",
    startDate: "2025-12-01",
    endDate: "2026-12-01",
    inflow: 18420000,
    outflow: 12100000,
    transactions: 2042,
    commission: 521000,
    deliveries: 612,
    bnplEnabled: true,
    logisticsAutomation: true,
    usage: { attendants: 14, inventory: 920, customers: 2210 },
    outlets: [
      { id: "out-1", name: "Sabon Gari HQ", location: "Kano" },
      { id: "out-2", name: "Tudun Wada Branch", location: "Kano" },
    ],
  },
  {
    id: "USR-10007",
    name: "Lagos Mart Ventures",
    businessName: "Lagos Mart Ventures",
    type: "Business",
    email: "kyc@lagosmart.io",
    phone: "+234 706 998 0011",
    address: "Yaba, Lagos",
    plan: "syncplus",
    planStatus: "active",
    status: "active",
    tier: "Tier 2",
    kycStatus: "re-upload",
    kycRef: { segment: "business", id: "biz-003" },
    joined: "2026-02-09",
    activeFor: "2 months",
    nextBilling: "2026-05-09",
    startDate: "2026-02-09",
    endDate: "2026-08-09",
    inflow: 3210000,
    outflow: 2410000,
    transactions: 410,
    commission: 78200,
    deliveries: 88,
    bnplEnabled: false,
    logisticsAutomation: true,
    usage: { attendants: 3, inventory: 220, customers: 488 },
    outlets: [
      { id: "out-1", name: "Yaba Mart", location: "Yaba, Lagos" },
      { id: "out-2", name: "Mushin Mart", location: "Mushin, Lagos" },
    ],
  },
];

export const findUser = (id) => SAMPLE_USERS.find((u) => u.id === id);

export const findPlan = (id) => SUBSCRIPTION_PLANS.find((p) => p.id === id);

export const formatLimit = (n) =>
  n === null || n === undefined ? "∞" : n.toLocaleString();
